---
-
  name: "strategy demo"
  hosts: webserver1, sqlserver1
  serial: 1
  tasks:
    -
      name: "first task"
      apt: name='apache2' state='present'
    -
      name: 'second task'
      command: touch /tmp/strategy_task2.txt
    -
      name: 'third task'
      command: sleep 60
