---
-
  name: "strategy demo"
  hosts: webserver1
  strategy: linear
  tasks:
    -
      name: "first task"
      apt: name='apache2' state='present'
    -
      name: 'second task'
      command: touch /tmp/strategy_task2.txt
